# Generated by Django 5.2.8 on 2025-11-29 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_group', models.CharField(choices=[('runner', 'Runner'), ('thrower', 'Thrower'), ('jumper', 'Jumper')], max_length=20)),
                ('sport_event', models.CharField(choices=[('100m', '100m Sprint'), ('200m', '200m Sprint'), ('400m', '400m Sprint'), ('800m', '800m'), ('1500m', '1500m'), ('3000m', '3000m'), ('5000m', '5000m'), ('10000m', '10000m'), ('shotput', 'Shot Put'), ('javelin', 'Javelin Throw'), ('hammer', 'Hammer Throw'), ('long_jump', 'Long Jump'), ('high_jump', 'High Jump')], max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('training_goal', models.CharField(choices=[('endurance', 'Endurance'), ('performance', 'Performance'), ('fat_loss', 'Fat Loss'), ('strength', 'Strength')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
