# Generated by Django 5.2.8 on 2025-12-07 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coachprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='users.coachprofile'),
        ),
    ]
