# Generated by Django 5.2.8 on 2025-12-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='average_heart_rate',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='sets_reps',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='sport_event',
            field=models.CharField(default='100m', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
